// EmailJS Configuration
// To set up EmailJS, follow these steps:

export const EMAILJS_CONFIG = {
  // 1. Go to https://www.emailjs.com/ and create a free account
  // 2. Create an email service (Gmail, Outlook, etc.)
  SERVICE_ID: import.meta.env.VITE_EMAILJS_SERVICE_ID || 'service_fixurfeed',
  
  // 3. Create an email template with these variables:
  //    - {{to_email}} - recipient email
  //    - {{to_name}} - recipient name  
  //    - {{subject}} - email subject
  //    - {{creators_list}} - plain text list of creators
  //    - {{html_content}} - HTML formatted creator cards
  TEMPLATE_ID: import.meta.env.VITE_EMAILJS_TEMPLATE_ID || 'template_matches',
  
  // 4. Get your public key from EmailJS account settings
  PUBLIC_KEY: import.meta.env.VITE_EMAILJS_PUBLIC_KEY || 'YOUR_PUBLIC_KEY_HERE',
};

// Template for EmailJS email template:
/*

Subject: {{subject}}

To: {{to_email}}

Body (HTML):
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>FixUrFeed Creator Matches</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { padding: 20px; }
        .creator-card { border: 1px solid #ddd; border-radius: 8px; padding: 15px; margin: 15px 0; background: #f9f9f9; }
        .creator-name { font-size: 18px; font-weight: bold; color: #667eea; margin-bottom: 5px; }
        .creator-role { color: #666; font-style: italic; margin-bottom: 10px; }
        .social-links a { color: #667eea; text-decoration: none; margin-right: 15px; font-weight: bold; }
        .social-links a:hover { text-decoration: underline; }
        .footer { background: #f8f9fa; padding: 20px; text-align: center; border-radius: 0 0 8px 8px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎯 Your FixUrFeed Creator Matches</h1>
        <p>Personalized recommendations for your tech and career journey</p>
    </div>
    
    <div class="content">
        <p>Hi {{to_name}}! 👋</p>
        <p>Here are your personalized creator matches based on your quiz responses:</p>
        
        {{{html_content}}}
        
        <p><strong>Start following them today to level up your career! 🚀</strong></p>
        
        <p>Questions? Reply to this email or visit <a href="https://fixurfeed.com">FixUrFeed.com</a></p>
    </div>
    
    <div class="footer">
        <p>Generated by <strong>FixUrFeed.com</strong></p>
        <p>Your personalized creator discovery platform</p>
        <p><small>You received this email because you requested your creator matches.</small></p>
    </div>
</body>
</html>

Plain text version:
Hi {{to_name}}!

Here are your personalized FixUrFeed creator matches:

{{creators_list}}

Start following them today to level up your career! 🚀

Visit FixUrFeed.com for more matches.

*/